server:
  servlet:
    context-parameters:
      module-context-path: /domrad
    context-path: /
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testtestdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true #wait for integrations of domain classes to the DB and then execute data.sql
  h2:
    console.enabled: true
    console.path: /h2-console

hibernate:
  hbm2ddl:
    auto: create

logging:
  level:
    org.hibernate.SQL: debug

